version: "3.8"

services:
  db-mysql:
    stdin_open: true
    environment:
      - MYSQL_ROOT_PASSWORD=secret1
      - MYSQL_DATABASE=projectsdb
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./projects-mysql-data:/var/lib/mysql
    tty: true
